package models

// ========================== ENUMS ==========================

type DotaGameRulesState int

const (
	INIT DotaGameRulesState = iota
	WAIT_FOR_PLAYERS_TO_LOAD
	HERO_SELECTION
	STRATEGY_TIME
	PRE_GAME
	GAME_IN_PROGRESS
	POST_GAME
	DISCONNECT
	TEAM_SHOWCASE
	CUSTOM_GAME_SETUP
	WAIT_FOR_MAP_TO_LOAD
	SCENARIO_SETUP
	LAST
)

type DotaGameMode int

const (
	DOTA_GAME_MODE_ALLPICK DotaGameMode = 1 + iota
	DOTA_GAME_MODE_CAPTAINS_MODE
	DOTA_GAME_MODE_RANDOM_DRAFT
	DOTA_GAME_MODE_SINGLE_DRAFT
	DOTA_GAME_MODE_ALL_RANDOM
	DOTA_GAME_MODE_INTRO
	DOTA_GAME_MODE_DIRETIDE
	DOTA_GAME_MODE_REVERSE_CAPTAINS_MODE
	DOTA_GAME_MODE_GREEVILING
	DOTA_GAME_MODE_TUTORIAL
	DOTA_GAME_MODE_MID_ONLY
	DOTA_GAME_MODE_LEAST_PLAYED
	DOTA_GAME_MODE_LIMITED_HEROES
	_
	_
	_
	DOTA_GAME_MODE_BALANCED_DRAFT = 17
	DOTA_GAME_MODE_ABILITY_DRAFT  = 18
	_
	DOTA_GAME_MODE_ALL_RANDOM_DEATH_MATCH = 20
	DOTA_GAME_MODE_SOLOMID                = 21
	DOTA_GAME_MODE_RANKED_AP              = 22
)

type MatchmakingMode int

const (
	MATCHMAKING_MODE_RANKED MatchmakingMode = iota
	MATCHMAKING_MODE_UNRANKED
	MATCHMAKING_MODE_SOLOMID
	MATCHMAKING_MODE_DIRETIDE
	MATCHMAKING_MODE_GREEVILING
	MATCHMAKING_MODE_ABILITY_DRAFT
	MATCHMAKING_MODE_TOURNAMENT
	MATCHMAKING_MODE_BOTS
	MATCHMAKING_MODE_HIGHROOM
	MATCHMAKING_MODE_TOURNAMENT_SOLOMID
	MATCHMAKING_MODE_CAPTAINS_MODE
	MATCHMAKING_MODE_LOBBY
	MATCHMAKING_MODE_BOTS_2X2
	MATCHMAKING_MODE_TURBO
)

type DotaPatch string

const (
	PATCH_DOTA_684       DotaPatch = "PATCH_DOTA_684"
	PATCH_DOTA_684_TURBO DotaPatch = "PATCH_DOTA_684_TURBO"
)

type Region string

const (
	REGION_RU_MOSCOW      Region = "ru_moscow"
	REGION_RU_NOVOSIBIRSK Region = "ru_novosibirsk"
	REGION_EU_CZECH       Region = "eu_czech"
)

type DotaTeam int

const (
	DOTA_TEAM_RADIANT DotaTeam = iota
	DOTA_TEAM_DIRE
)

type DotaConnectionState int

const (
	DOTA_CONNECTION_STATE_UNKNOWN DotaConnectionState = iota
	DOTA_CONNECTION_STATE_NOT_YET_CONNECTED
	DOTA_CONNECTION_STATE_CONNECTED
	DOTA_CONNECTION_STATE_DISCONNECTED
	DOTA_CONNECTION_STATE_ABANDONED
	DOTA_CONNECTION_STATE_LOADING
	DOTA_CONNECTION_STATE_FAILED
)
