name: Go Sidecar CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # Build the Go binary
      - name: Build Go binary
        run: |
          go build -o sidecar main.go

      # Run tests if any
      - name: Run tests
        run: |
          go test ./...
